version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "gomod"
    directory: "/client"
    schedule:
      interval: "weekly"

- package-ecosystem: "gomod"
    directory: "/server"
    schedule:
      interval: "weekly"
